["gcp_service_account"]
type = "service_account"
project_id = "register2025"
private_key_id = "2f0a238d6cb5bd283cbb8f992f3e8903ebea8f40"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtRdKpri2JnokA
HizJheWCYhNml9s6acu6BqRMTlb29h0e3Qlrv2xXg4tRmwvtulBtFl4uZ2g7+uwn
4UDvaA5rngtM8lxKNX/qodJJRj8Hqe4NCmIvrQQjl6vvfDNoVoC0KpRr5j7v5fI4
SqACjXa2aWHIYdzfxpewkpjgfeiurJHFaY+ibeKoG0q6bW5o1z76iFfnBJYU2mAR
C8PwMff+DVBf1UnEA69vwneuapVLdP1ukyd0gZgoVOvGAvCfQY6Cv5KsiPWlepRP
2f3mafxo1h8nUGiNRIBBs4hZ3VqVuRZ/MDzVOZWupO3XrGfOgVIucqaJgK6qBetZ
Ggir+N7FAgMBAAECggEAGxFzTWqWVo9bm5cbLAgsyGeF3FsQtllcqBztgbYjQ8VC
21VwaVKoHCvCkecEwAiBE+mQoPMqh2Q1jC1WNZAt4IX6AfVCkZ019HN/JE9C/XGA
bK0YlZYTtXO2Ol1OspgA1yRnt0tqvZNQeZa+1GdBClIAIouXM6YUgFMGatuAg/jT
A7p+vlkO/xb0EUhzxGQ48vo91xQXfxBcFhGsc7dQD+QbcMWf+o/iCRsGfMt2OVIT
rC+Cvmk2J4ZfzRCjIpT2LEbquQ8IDvvgooPdYYu2e7HxFxtAPI+ElXT7Tkr6sxkJ
xmlZqSsPVUBJyPOjMP+lAJ5+rFy8znpCFRpKMIBW6QKBgQDyD/TL4mRwhlf8ULDS
0dFCFkyhsBiv0xdQkaIm2sgANWxF/b8J1PYVGPHK7sJUieKdZ8V/5osFNP+sPxs3
DVgEIBtuSUUYuXpFi7J6Qc8UayJZ94NSYOWexh1WTt+NB7opG7MhMdy2gNaD21IK
QO4xCHrsUKhrrBy/Y4BVLbRZvwKBgQC3P+U5jVT6GtAUciAZ1++zMngAy81hDU4o
sSDWHCvPsh7U82N+/c85y6lTySkNegASWtcVRyaE7esxvQE5kIJzmZMdIw8GVF+J
KvZB2Emwi4TxBOJbcQpJIO4LJ0oxbBiCrnmnzXP2ucsJlf9YFgfNYBdziWzcipyX
vxSXxJ5AewKBgQCGmHq8t7iznO/lm5SG1SYvQikAKuO/OHgZU7E/O53EB/CZhnuo
YuMmXgVsmpAx462/aok2EiIxFgQoabqfROsw+A1oqJMkKVYkv4XRVzBnIR8ruWYq
8zgarfx4FklVqPtJil5zUb9xN3iQPu6CRxJq71Uye7L6k+w0O4aLVmuXDwKBgFgi
+jw5FtMITGZZEcl8S4Sz1HYFj+2K+bmmn/V7LTNDJ4Mi4Qr2RlI0+2caDI23zQsG
+AX657Ltv753enxWXff9uH0+HH7d2+lcaX736VFpeXJ29+wlLV5I4VUp+4xTwmIw
SsEDly/m4pnktCCI0A3elsjyIxLb9D8kH2Jzpe27AoGBAJyRQ+mwFmgpYYUJBhPG
m8TEqJf21l3eLS5wG9vG4NTEZ2FmVnhws5arU/AHwQY/750jKsGBEycnW1x5zlA4
zjr8VOwOIFUW20GVFXNota3npzsB1vm0kRPTCW68kQpFff+2KIY6aHTHSISC8z71
B8OOVLSDV6Xiv6ZF7Sp0SGh9
-----END PRIVATE KEY-----"""
client_email = "register@register2025.iam.gserviceaccount.com"
client_id = "114933885156882369972"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/register%40register2025.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
